# Numerical problems on cytoplasmic inheritance, sex linked inheritance and sex determination

## Question 1

A sex-linked recessive allele c produces a red-green color blindness in humans. A normal woman whose father was color blind marries a color-blind man. 
a. What genotypes are possible for the mother of the color blind man ? 
b. What are the chances that the first child from this marriage will be a color-blind boy ? 
c. Of the girls produced by these parents, what proportion can be expected to be color blind ? 
d. Of all the children (sex unspecified) of these parents, what proportion can be expected to have normal color vision ?

## Question 2

The recessive gene e, produces color blind in human, which is sex linked gene. A carrier woman of this gene married a color blind man and produced first child, a normal vision klinefelter but in the second time this couple gave birth a color blind daughter. How such klinefelter and daughter may be produced? Show with the help of clean diagram.

## Question 3

In maize, recessive gene ba produces barren cob and ts gene converts male flower into female flower. Ba and Ts are the dominant genes give the normal cob and male flowers, respectively. A genetician working at IAAS crossed a plant having genotype Baba Tsts with other plant having genotype BaBa Tsts. Show this cross and determine the sex expression in the progeny.
