---
title: "Numerical Problems"
author: |
  | Deependra Dhakal
  | Gokuleshwor Agriculture and Animal Science College, Baitadi, Nepal
date: "9/18/2020"
output: 
  bookdown::pdf_document2:
    keep_tex: yes
    toc: false
    includes:
      in_header: gen_solutions_header.tex
documentclass: exam
classoption: "answers,addpoints,12pt"
geometry: "top=1.5cm,bottom=1.5cm,left=1.5cm,right=1.5cm"

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = TRUE, message = FALSE, warning = FALSE)
options(knitr.kable.NA = '')
require(tidyverse)
```


##

In maize, recessive gene ba produces barren cob and ts gene converts male flower into female flower. Ba and Ts are the dominant genes and together they give the normal cob and male flower respectively. A genetician crossed a plant having genotype BabaTsts with other plant haivng genotype BaBaTsts. Show this cross and determine the sex expression in the progeny.

## Problem 1: Sex linked inheritance

A sex-linked recessive allele $c$ produces a red-green color blindness in humans. A normal woman whose father was color blind marries a color-blind man.
  a. What genotypes are possible for the mother of the color blind man ?
  b. What are the chances that the first child from this marriage will be a color-blind boy ?
  c. Of the girls produced by these parents, what proportion can be expected to be color blind ?
  d. Of all the children (sex unspecified) of these parents, what proportion can be expected to have normal color vision ?
  
## Solution 1: Sex linked inheritance

a. $X^C/X^c, X^c/X^c$
b. p (color-blind) x p (\male) = (1/2)(1/2) = 1/4
c. The girls will be 1 normal ($X^C/X^c$): 1 color-blind ($X^c/X^c$).
d. The cross is $X^C/X^c \times X^c/Y$, yielding 1 normal:1 color-blind for both sexes.
