--- 
title: "A practice book for Introductory Genetics"
subtitle: "Student's guide"
author: "Deependra Dhakal"
site: bookdown::bookdown_site
# output: bookdown::gitbook
output: 
  bookdown::pdf_document2:
    keep_tex: yes
    toc: yes
    includes:
      in_header: tex/preamble.tex
documentclass: book
classoption: openany # this will force for 2 side layout of book to open chapter at any side
geometry: "top=2cm,bottom=1.5cm,left=1.5cm,right=1.5cm"
bibliography: [bib/bibliography.bib]
biblio-style: apalike
link-citations: yes
# github-repo: deependrad/practical-genetics
description: "This handout is intended as a supplementary material for practical in Introductory Genetics course in undergraduate level"
---

```{r setup, include=FALSE, message=FALSE}
require(knitr)
knitr::opts_chunk$set(tidy = TRUE, cache = TRUE, 
                      echo = FALSE, 
                      tidy.opts = list(width.cutoff=50), 
                      eval = TRUE, warning = FALSE, message = FALSE,
                      # fig.show = "hold", 
                      fig.align = "center", fig.width = 6,
                      fig.asp = 0.9, out.width = "0.85\\linewidth")
options(knitr.kable.NA = "", digits = 3, knitr.table.format = "latex")
options(kableExtra.latex.load_packages = FALSE)
require(kableExtra)
require(tidyverse)
ggplot2::theme_set(theme_bw())
```

```{r include=FALSE}
# # automatically create a bib database for R packages
# knitr::write_bib(c(
#   .packages(), 'bookdown', 'knitr', 'rmarkdown', "dplyr", "purrr"
# ), './bib/packages.bib')
```

<!-- # Introduction -->

<!-- This is a reference manual for self purpose only. -->
