# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

name: R-xaringan-build
jobs:
  R-xaringan-build:
    runs-on: 'ubuntu-16.04'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Setup R  
        uses: r-lib/actions/setup-r@master
      
      - name: Install pandoc and pandoc citeproc
        run: |
          sudo apt-get install pandoc
          sudo apt-get install pandoc-citeproc
      
      - name: Install debian packages
        run: |
          sudo apt-get install libcurl4-openssl-dev libpoppler-cpp-dev libpoppler-dev chromium-browser
          
      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ~/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-
      
      - name: Cache bookdown results
        uses: actions/cache@v2
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-
          
      - name: Restore packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'
      
      - name: Render HTML slide
        run: |
          setwd("./PLB221_introductory_plant_breeding/plb221_presentation/")
          xaringan::infinite_moon_reader("./02-domestication_plant_introduction_and_acclimatization_html.Rmd")
          pagedown::chrome_print("./02-domestication_plant_introduction_and_acclimatization_html.html")
          setwd("../../")
        shell: Rscript {0}
      
      - name: Upload artifacts to local repository
        uses: actions/upload-artifact@v1
        with:
          name: _book
          path: _book/
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit "./PLB221_introductory_plant_breeding/plb221_presentation/02-domestication_plant_introduction_and_acclimatization_html.pdf" -m 'Re-build second lecture' || echo "Second lecture rebuilt"
          git push origin || echo "Second lecture rebuilt"