# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  RENV_PATHS_ROOT: ~/.local/share/renv

name: R-xaringan-build
jobs:
  R-xaringan-build:
    runs-on: 'ubuntu-16.04'
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install debian packages
        run: |
          sudo apt-get install libcurl4-openssl-dev
      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
      - name: Render HTML slide
        run: |
          setwd("./PLB221_introductory_plant_breeding/plb221_presentation/")
          Rscript -e 'xaringan::infinite_moon_reader("./02-domestication_plant_introduction_and_acclimatization_html.Rmd")'
          setwd("../../")
        shell: Rscript {0}
      - uses: actions/upload-artifact@v1
        with:
          name: _book
          path: _book/
        