# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: R-xaringan-build
jobs:
  R-xaringan-build:
    runs-on: 'ubuntu-16.04'
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("tidyverse", "devtools", "xaringan", "webshot"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
        