# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

name: R-xaringan-build
jobs:
  R-xaringan-build:
    runs-on: 'ubuntu-16.04'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Setup R  
        uses: r-lib/actions/setup-r@master
      
      - name: Install pandoc and pandoc citeproc
        run: |
          sudo apt-get install pandoc
          sudo apt-get install pandoc-citeproc
      
      - name: Install debian packages
        run: |
          sudo apt-get install libcurl4-openssl-dev libpoppler-cpp-dev libpoppler-dev chromium-browser
          
      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ~/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-
      
      - name: Cache bookdown results
        uses: actions/cache@v2
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-
          
      - name: Restore packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'
      
      - name: Render HTML slide
        run: |
          # Set working directory
          setwd("./PLB221_introductory_plant_breeding/plb221_presentation/")
          
          # List all html outputing Rmd files
          rmd_file_list <- list.files(".", "_html.Rmd$")
          html_file_list <- gsub(".(Rmd)$", replacement = ".html", rmd_file_list)
          purrr::map(rmd_file_list, ~rmarkdown::render(.x))
          
          # chrome print (it would be better if any way to only print changed html files?)
          purrr::map(html_file_list, purrr::possibly(~pagedown::chrome_print(.x), otherwise = FALSE))
          
          # list all rmd --> html --> pdf files
          pdf_file_list <- list.files(".", "_html.pdf$")
          
          # go to top directory
          setwd("../../")
          
          dir.create('_book', showWarnings = T)
          purrr::map(pdf_file_list, 
              ~file.rename(paste0("./PLB221_introductory_plant_breeding/plb221_presentation/", .x), paste0("_book/", .x)))
          list.files("_book/")
        shell: Rscript {0}
      
      - name: Upload artifacts to local repository
        uses: actions/upload-artifact@v1
        with:
          name: _book
          path: _book/
      # 
      # - name: Commit results
      #   run: |
      #     git config --local user.email "actions@github.com"
      #     git config --local user.name "GitHub Actions"
      #     git add _book/*
      #     git commit -m 'Lectures rebuilt to pdfs' || echo "Lectures rebuilt to pdfs"
      #     git push origin || echo "Lectures rebuilt to pdfs and uploaded"
