---
title: Genetic composition of cross pollinated populations
author: Deependra Dhakal
date: Academic year 2019-2020 
institute: |
  | Gokuleshwor Agriculture and Animal Science College
  | Tribhuwan University
  | \textit{ddhakal.rookie@gmail.com}
  | \url{https://rookie.rbind.io}
output: 
  binb::metropolis:
    includes:
      in_header: beamer_header_template.tex
classoption: "aspectratio=169" # "compressed"
fontsize: 11pt
bibliography: [./../../bibliographies.bib]
---

```{r,setup, include=FALSE}
library(knitr)
require(tidyverse)
set.seed(453)
# invalidate cache when the package version changes
knitr::opts_chunk$set(tidy = FALSE, echo = FALSE, 
                  message = FALSE, warning = FALSE,
                  out.width = "45%", cache = TRUE)
options(knitr.table.format = "latex")
options(knitr.kable.NA = "", digits = 2)
options(kableExtra.latex.load_packages = FALSE)
```

# Introduction

##

# Introduction

- A population is a group of sexually interbreeding individuals.
- The capacity to interbreed implies that every gene within the group is accessible to all members through the sexual process.
- A gene pool is the total number and variety of genes and alleles in a sexually reproducing population that are available for transmission to the next generation.
- The genetic structure of a population determines its capacity to be changed by selection (i.e., improved by plant breeding)
- The genetic constitution of a population is described by an array of gene frequencies. 
- The genetic properties of a population are influenced in the process of transmission of genes from one generation to the next by four major factors - *population size*, *differences in fertility and viability*, *migration and mutation*, and the *mating system*.
- Breeding of cross-pollinated species tends to focus on population improvement rather than individual plants.
- Rather than inheritance of traits, *genetics of population* is concerned with how the frequencies of alleles in a gene pool change over time.

---

# Hardy-weinberg law 

- The genetic constitution of individuals in a population is reconstituted for each subsequent generation whereas the genes carried by the population have continuity from one generation to the next.
- Plant breeders often work with genetic phenomena in populations that exhibit no apparent Mendelian segregation, even though in actuality, they obey Mendelian laws. 
- Mendel worked with genes whose effects were categorical (kinds) and were readily classifiable (ratios) into kinds in the progeny of crosses. 
- Breeders, on the other hand, are usually concerned about differences in populations measured in degrees rather than kinds. 
- Population genetics uses mathematical models to attempt to describe population phenomena. It is, thus, necessary to make assumptions about the population and its environment.

---

## Calculating gene frequency

- Gene frequencies are simply the proportions of the different alleles of a gene in a population.
- To obtain these proportions we count the total number of organisms with various genotypes in the population and estimate the relative frequencies of the alleles involved.
- To understand the genetic structure of population, consider a large population in which random mating occurs, with no mutation or gene flow between this population and others, no selective advantage for any genotype, and normal meiosis.

---
- Consider also one locus, $A$, with two alleles, $A$ and $a$. The frequency of allele $A_1$, in the gene pool is $p$, while the frequency of allele $A_2$ is $q$. Also, $p + q = 1$ (or 100% of the gene pool). Assume a population of $N$ diploids in which two alleles ( $A$, $a$) occur at one locus.

- Assuming dominance at the locus, three genotypes – $AA$, $Aa$ and $aa$ – are possible in an $F_2$ segregating population. Assume the genotypic frequencies are $D$ (for $AA$), $H$ (for $Aa$) and $Q$ (for $aa$). Since the population is diploid, there will be $2N$ alleles in it. The genotype $AA$ has two $A$ alleles. Hence, the total number of $A$ alleles in the population is calculated as $2D + H$. The proportion or frequency of $A$ alleles (designated as $p$) in the population is obtained as follows.

$$
\begin{aligned}
\frac{2D + H}{2N} = D + \frac{1}{2}H = p
\end{aligned}
$$

The same can be done for allele $a$, and designated $q$. Further, $p + q = 1$ and hence $p = 1-q$.

---

## Numerical example

If $N = 80$, $D = 4$ and $H = 24$. (Here, D and H are rather used as count of individuals rather than frequencies)

Genotypic frequencies; 
$$
\begin{aligned}
D = 4/80 \\
H = 24/80 \\
Q = 52/80
\end{aligned}
$$
Now,

$$
p = \frac{D + \frac{1}{2}H}{N} = \frac{4 + 12}{80} = \frac{16}{80} = 0.2
$$

Since $p + q = 1$, $q = 1-p$, and hence $q = 1-0.2 = 0.8$.

---

# HW Equilibrium

- Consider a random mating population (each male gamete has an equal chance of mating with any female gamete). 
- Random mating involving the previous locus (A/a) will yield the following genotypes: $AA$, $Aa$, and $aa$, with the corresponding frequencies of $p^2+2pq+q^2$, respectively. 
- The gene frequencies must add up to the unity. Consequently, $p^2+2pq+q^2 = 1$. This mathematical relationship is called Hardy-Weinberg equilibrium. 
- Hardy, from England, and Weinberg, from Germany, discovered that equilibrium between genes and genotypes is achieved in large populations. 
- They showed that the frequency of genotypes in a population depends on the frequency of genes in the preceding generation, not on the frequency of the genotypes.

---

# HW Equilibrium

Considering the previous example, the genotypic frequencies for the next generation following random mating can be calculated as follows:

$$
\begin{align}
AA &= p^2 &= 0.2^2 &= 0.04 \\
Aa &= 2pq &= 2 (0.2\times0.8) &= 0.32 \\
aa &= q^2 &= 0.8^2 &= 0.64
\end{align}
$$
- The Hardy-Weinberg equilibrium is hence summarized as:

$$
p^2AA + 2pqAa + q^2aa = 1
$$

---

- This means that in a population of 80 plants as before, about three plants will have a genotype of $AA$, 26 will be $Aa$, and 51, $aa$. Using the previous formula, the frequencies of the genes in the next generation may be calculated as:

$$
P = \frac{D + \frac{1}{2} H}{N} = \frac{3+13}{80} = 0.2
$$

And, $q = 1-p = 0.8$

- The allele frequencies have remained unchanged, while the genotypic frequencies have changed (for AA, Aa, and aa, respectively) from 4, 24, and 52, to 3, 26, and 51.
- However, in subsequent generations, both the genotype and gene frequencies will remain unchanged, provided that:
  - Random mating occurs in a very large diploid population;
  - Allele $A$ and allele $a$ are equally fit (one does not confer a superior trait than the other);
  - There is no differential migration of one allele into or out of the population;
  - The mutation rate of allele $A$ is equal to that of allele $a$.

---

# Changing gene and genotypic frequencies in HW population

?figure?

The relationship between allele frequencies and genotype frequencies in a population in Hardy–Weinberg equilibrium for two alleles. The frequency of the heterozygotes cannot be more than 50%, and this maximum occurs when the allele frequencies are $p=q=0.5$. Further, when the frequency of an allele is low, the rare allele occurs predominantly in heterozygotes and there are very few homozygotes. (Adapted from Falconer, 1981.)

---

## Summary of HW principle

- Hence the stability of genotypic frequency after the first generation is said to be in equilibrium.
- This genotypic equilibrium, based on stable gene frequencies and random mating, is known as Hardy-Weinberg principle (or law)
- Hence, Genetic differences in a randomly breeding population will tend to remain constant unless acted upon by external forces.
- In other words, the variability does not change from one generation to another in a random mating population. 
- The maximum frequency of the heterozygote (H) cannot exceed 0.5. The Hardy-Weinberg law states that equilibrium is established at any locus after one generation of random mating. 

---

## Plant Breeding implications of HW principle

- From the standpoint of plant breeding, two states of variability are present – two homozygotes (AA, aa), called “free variability” that can be fixed by selection and the intermediate heterozygous (Aa), called “hidden or potential variability, that can generate new variability through segregation.
- In outcrossing species, the homozygotes can hybridize to generate more heterozygotic variability. Under random mating and no selection, the rate of crossing and segregation will be balanced to maintain the proportion of free and potential variability of 50%:50%.
- However, with two loci under consideration, equilibrium will be attained slowly over many generations.
- If genetic linkage is strong, the rate of attainment of equilibrium will be even much slower.

---

## Plant Breeding application of HW principle

- In disease resistance breeding, plant breeders cross an elite susceptible cultivar with one that has disease resistance. Consider a cross between two populations, susceptible x resistant. If the gene frequencies of an allele $A$ in the two populations are represented by $P_1$ and $P_2$, the gene frequency in the $F_1 = \frac{P_1 + P_2}{2} = p$. Assuming the frequency of the resistance gene (Note here that same allele is being considered) in the resistant cultivar is $P_1=0.7$ and that in the susceptible elite cultivar is $P_2=0.05$, the gene frequency in the progeny of the cross p would be obtained as follows: 
$p = \frac{P_1 + P_2}{2} = (0.7 + 0.05)/2 = 0.375$
- Consequently, the gene frequency for the resistant trait is reduced by about 50% (from 0.7 to 0.375).

---
class: inverse, middle, center

# Forces changing gene frequencies

---

# Mutation

- Introduces a particular gene into a population
- A unique mutation (non-recurrent mutation) would have little impact on gene frequencies.
- Types: forward and reverse mutation (Based on the direction of mutation)
  - Wild type (A) $\rightarrow$ Mutant type (a)
  - Mutant type (a) $\rightarrow$ Wild type (A)
- Even if the rate of mutation of A to a is small, after a large number of generations, A will disappear.

---

# Selection and fitness

- One of the most important causes for the change in gene frequency lies in the ability of its carriers to produce surviving offspring.
- If individuals carrying gene A are more successful in reproduction, than those carrying a, the frequency of former tends to be greater than the latter.
- Wide variety of mechanisms responsible for reproductive success of a genotype is known collectively as *selection*.
- Artificial and Natural selection
- *Fitness* has a variety of applied meanings, but generally refer to ability and aptitude.
- In genetic sense, it is far more restricted to relative reproduction success.
- Whether a genotype appears superficially “weak” or “strong”, “beautiful” or “ugly”, may be of no matter, only when a genotype can produce more offspring than another in the same environment, is its fitness superior.

---

# Migration

- A population may receive alleles by migration from a nearby population that maintains an entirely different gene frequency.
- Two factors are important for recipient population in this case:
  - The difference in frequencies between the two populations and 
  - The proportions of migrant genes that are incorporated each generation

---

# Random genetic drift

- When unopposed the previously discussed forces (Mutation, selection and migration) can lead of fixation of one allele and elimination of all others, or, when balanced, they can lead to equilibrium between two or more alleles.
- However, Random genetic drift is one of the most important non-directional forces that arises from variable sampling of the gene pool each generation and is known as random genetic drift.
- Genetic drift is caused by the fact that real populations are limited in size rather than infinite, so that gene-frequency changes occur because of sampling errors.
- Example: If only a few parents are chosen to begin a new generation, such a small sample of genes may deviate widely from the gene frequency of the previous generation.

---

# Mating systems
