---
title: "Plant Breeding Organizations"
author: "Deependra Dhakal"
date: "2019/04/04 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      ratio: '16:9'
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: inverse, middle, center

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
options(knitr.kable.NA = "", digits = 3)
knitr::opts_chunk$set(tidy = FALSE, echo = FALSE)
```

<style type="text/css">
.title-slide {
background-color: green;
}
.small-font {
    font-size: 40%;
}
.medium-font {
    font-size: 75%;
}
</style>

# National organizations related to crop improvement

---

**National Agricultural Research Council**

1. National Rice Research Program (NRRP): Hardinath, Dhanusa
2. National Wheat Research Program (NWRP): Bh airahawa, Rupendehi
3. National Maize Research Program (NMRP) Rampur, Chitwan
3. National Grain Legumes Research Program ( NGLRP) Rampur, Chitwan
4. National Oilseeds Research Program (NORP): Nawalpur, sarlahi
5. National Sugarcane Research Program (NSRP): Jitpur, Bara
6 . National Jute Research Program (NJRP): Itahari, Sunsari
7. Cotton Development Program : Khajura, Nepaljung
8. Coordinated Maize Program (CMO): Khumaltar, Lalitpur.
9. Institute of Agriculture and Animal Science (IAAS): Rampur, Chitwan

---

**Objectives**

- To conduct high level studies and researches on various aspects of agriculture
- To identify the existing problems in agriculture and find out measures to solve
- To assist His Majesty's Government in the formulation of agricultural policies and strategies

**Functions and Responsibilities**

- Conduct high level research work on various fields of agriculture required in the line with the national agricultural policies,
- Prioritize studies and researches to be conducted,
- Provide research and consultancy services to its clients,
- Coordinate, monitor and evaluate the agriculture research activities in Nepal, 
- Document research activities

---

**Mandates**

- To conduct and/or let to conduct agricultural research,
- To determine priorities in studies and research related to agriculture,
- To provide consultant services and research support services to agricultural research,
- To coordinate, supervise, monitor, review and evaluate research activities related to agriculture in the country,
- To maintain/document up-to-date records of agricultural research, and
- To conduct and /or let to conduct other necessary activities related to agricultural research.

---

**Department of Agriculture Development**

1. Division of Horticulture, Kirtipur, Kathmandu
2. Division of vegetable, Khumaltar, Lalitpur
3. Horticulture Farm, Daman/Marpha/Solukhumbu/Sarlahi/Sindhuli/Dolkha/ Panchkhal/Godawari/Kirtipur/Trisuli/Mustang/Palpa/Jumla/Dailekh/Baitadi/Humla/Chitwan

**Department of Plant Resources**

1. National Herbarium and Plant laboratory, Godawari, Lalitpur - leading role in conservation of medicinal plants
2. Herbal conservatory, Hetauda/ Daman/ Tistung, Makwanpur

---
class: inverse, middle, center

# International organizations related to crop improvement

---

1. IRRI ( International Rice Research Institute): Los Banos, Philippines
2. CIMMYT ( International Centre for Maize and Wheat Improvement): el Baton, Mexico
3. CIAT ( International Centre for Tropical Agriculture): Palmira, Colombia
4. IITA ( International Institute of Tropical Agriculture): Ibadan, Nigeria
5. WARDA ( West African Rice Development Association): Monrovia, Liberia
6. CIP ( International Centre for Potato): Lima, Peru
7. ICRISAT ( International Crops Research Institute for the Semi-Arid Tropics) : Hyderabad, India
8. IBPGR (International Board for Plant Genetic Resources) : Rome, Italy.
9. ICARDA (International Centre for Agricultural Research in Dry Areas): Aleppo, Syria
10. ICGEB (International Centre for Genetic Engineering and Biotechnology): Italy and India
11. AVRDC (Asian Vegetable Research and Development Centre): Taiwan